# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  - master

pool:
  name: Cat Breeds Detector

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"

steps:
  - checkout: self
    fetchDepth: 0

  - task: PowerShell@2
    displayName: "Clear agent's folder content"
    inputs:
      targetType: 'inline'
      script: |
        Remove-Item  $(System.DefaultWorkingDirectory)\* -Recurse
        Write-Host The contents of the folder: $(System.DefaultWorkingDirectory) cleared.

  - task: UseDotNet@2
    displayName: 'Use .NET 7'
    inputs:
      packageType: 'sdk'
      version: '7.x'
  
  - task: DotNetCoreCLI@2
    displayName: "Restore solution"
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      verbosityRestore: 'Normal'

  - task: NuGetToolInstaller@1
    displayName: "Nuget tool installer"

  - task: VisualStudioTestPlatformInstaller@1
    displayName: "Install VS Test Platform"
    inputs:
      packageFeedSelector: "nugetOrg"
      versionSelector: "latestStable"

  - task: SonarCloudPrepare@1
    displayName: 'Prepare Sonar Cloud analysis configuration'
    inputs:
      SonarCloud: 'Sonar cloud'
      organization: 'ya-software-azure'
      scannerMode: 'MSBuild'
      projectKey: 'YASoftware_Cat-breeds-detector'
      projectName: 'Cat breeds detector'

  - task: VSBuild@1
    displayName: "Build solution"
    inputs:
      solution: "$(solution)"
      msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
      platform: "$(buildPlatform)"
      configuration: "$(buildConfiguration)"
  
  - task: SonarCloudAnalyze@1
    displayName: 'Run Sonar Cloud analysis'
    
  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'

  - task: VSTest@2
    displayName: "Unit Tests"
    inputs:
      testSelector: "testAssemblies"
      testAssemblyVer2: |
        **\CatBreedsDetector.UnitTests.dll
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)\test'
      codeCoverageEnabled: true

  - task: VSTest@2
    displayName: "Classification Integration Tests"
    inputs:
      testSelector: "testAssemblies"
      testAssemblyVer2: |
        **\CatBreedsDetector.Classification.Integration.dll
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)\test'
      codeCoverageEnabled: true

  - task: VSTest@2
    displayName: "Service Integration Tests"
    inputs:
      testSelector: "testAssemblies"
      testAssemblyVer2: |
        **\CatBreedsDetector.Services.Integration.dll
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)\test'
      codeCoverageEnabled: true
  - task: VSTest@2
    displayName: "Server Integration Tests"
    inputs:
      testSelector: "testAssemblies"
      testAssemblyVer2: |
        **\CatBreedsDetector.Server.Integration.dll
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)\test'
      codeCoverageEnabled: true
